services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local1234!
      POSTGRES_DB: localDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - local-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    networks:
      - local-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  local-network:
    driver: bridge
